version: '1.0'

services:
  migrate:
    build: .
    container_name: migrate
    command: python manage.py migrate
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"

  web:
    build: .
    container_name: triggery_backend
    command: gunicorn triggery.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_broker
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A triggery worker -l INFO
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A triggery beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env

volumes:
  postgres_data:
