# Generated by Django 5.1.7 on 2025-03-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
