# Generated by Django 5.1.7 on 2025-03-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="trigger_name",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
