# Generated by Django 5.1.7 on 2025-03-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_eventlog_is_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_test", models.BooleanField(default=False)),
                (
                    "cron_expression",
                    models.CharField(
                        help_text="Cron format: minute hour day month day_of_week (optional: year)",
                        max_length=128,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
