# Generated by Django 5.1.7 on 2025-03-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_recurringtrigger"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apitrigger",
            old_name="payload",
            new_name="schema",
        ),
    ]
