# Generated by Django 5.1.7 on 2025-03-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_payload_apitrigger_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringtrigger",
            name="cron_expression",
            field=models.CharField(
                help_text="Cron format: */5 * * * * (Please look at: https://crontab.guru for generating Cron Expressions.)",
                max_length=128,
            ),
        ),
    ]
