# Generated by Django 5.1.7 on 2025-03-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_recurringtrigger_cron_expression"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="eventlog",
            name="is_test",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
