name: License scan on tags

on:
  push:
    tags:
      - '*'

jobs:
  compliance_check:
    runs-on: ubuntu-latest
    name: Perform license scan
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get current tag
      id: current_tag
      run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

    - name: License check on tagging a new version
      id: compliance
      uses: fossology/fossology-action@v1
      with:
        scan_mode: "differential"
        scanners: "ojo keyword"
        from_tag: "v1.0.0"
        to_tag: ${{ steps.current_tag.outputs.tag }}
        report_format: "SPDX_JSON"
